### PR TITLE
Version 1.1.1 - Optimizer Update

### PR DESCRIPTION
**Pull request by zfi**
* Update compiler optimization flag to optimize for size.
* Update version number to 1.1.1
* Update .gitignore to exclude shell scripts from the repo.

### CODE REVIEW

**Comment by PropGit** [comment]
Is that safe for all applications?

**Comment by zfi** [comment]
It's safe for the apps targeted for the specific hardware Matt is testing. I'm not convinced that this change has been properly regression tested. It is why I have not merged the PR.

**Comment by PropGit** [comment]
Me either.  I've seen various optimizations cause unexpected problems from time to time, which is why they are _options_ and not something enabled _always_.  This will probably be something we ultimately need to expose as an option to the UI.

**Comment by PropGit** [comment]
Strange... I can see @MatzElectronics reply in email, but not in this thread.  Regardless, I'll answer.

You raise a good question.  At first I was thinking it'd be a setting tied to the user account, but that really doesn't make sense because it has the possibility of causing perfectly good projects to fail, but only for that user.  Bad.  For this reason, it really _should_ be a block that the project user/developer can add to the project, so that it behaves the same for each user that uses it, while projects without it don't compile with that option.

**Comment by zfi** [comment]
Right. The default optimization should be set to Oh-Zero (-O0) Add the project options block only when one needs to override any of the default settings.  My only concern, so far, with exposing this as a block is that it would be the only block that does not actually generate any code.

**Comment by michel-cf** [comment]
You still have the project settings. Wouldn't that be a better option in this case?

I always thought of the project settings page as a kind of wizard, with multiple tabs. I would think setting compiler options is also a feature for more advanced users. So I wouldn't put it too much front and center.

**Comment by zfi** [comment]
Good to hear from you Michel. I hope all is well with you and your family.

This is the first time we have had to address a project configuration that was not expressed as a blockly block. I have been looking for the project settings In the BlocklyProp project but am not able to find this. I might have been in an older branch that has been deleted.

It looks like we are going to drop this PR and go back and think about this more carefully before releasing a project settings feature.

**Comment by michel-cf** [comment]
I'm good, due to a lot of work at the office, and since I bought a house last year in which I'm doing a lot of projects I don't have a lot of time to work on the projects. And a lot of it is writing blocks and gui work, things I don't like and am not good in. The Cloud-compiler has always been my favorite and that is then also the only one that I follow and have a look at when a merge request is created.

[The generated project class](https://github.com/parallaxinc/BlocklyProp/blob/master/src/main/java/com/parallax/server/blocklyprop/db/generated/tables/Project.java)

[The project form](https://github.com/parallaxinc/BlocklyProp/blob/master/src/main/webapp/WEB-INF/includes/pageparts/projectform.jsp)

[The project servlet](https://github.com/parallaxinc/BlocklyProp/blob/master/src/main/java/com/parallax/server/blocklyprop/servlets/ProjectServlet.java)

And when a [compilation request](https://github.com/parallaxinc/BlocklyProp/blob/master/src/main/java/com/parallax/server/blocklyprop/rest/RestCompile.java) is done, you will have to add the compiler options to the [request](https://github.com/parallaxinc/Cloud-Compiler-java-client/blob/master/src/main/java/com/parallax/client/cloudcompiler/CCloudCompileService.java) to the cloud-compiler.

**Pull request merged**
